# Generated by Django 5.1.1 on 2024-10-08 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("index", "0007_doctor_specialization"),
    ]

    operations = [
        migrations.CreateModel(
            name="records",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doa", models.DateField()),
                ("condition", models.CharField(max_length=50)),
                ("medical_advice", models.CharField(max_length=50)),
                ("medications", models.CharField(max_length=50)),
                (
                    "did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.doctor"
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.patient"
                    ),
                ),
            ],
        ),
    ]
