# Generated by Django 5.1.1 on 2024-10-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(default="pending.."),
        ),
    ]
