# Generated by Django 5.1.1 on 2024-10-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_appointment_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="appointment",
        ),
    ]
