# Generated by Django 5.1.1 on 2024-10-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="patient",
            fields=[
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "Id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("aadhar", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PatientInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("medical_history", models.TextField(blank=True, null=True)),
                ("current_medications", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("chronic_conditions", models.TextField(blank=True, null=True)),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("blood_type", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "covid_vaccination_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "flu_vaccination_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "primary_care_physician",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("specialist", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.patient"
                    ),
                ),
            ],
        ),
    ]
