# Generated by Django 5.1.1 on 2024-10-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_hospital"),
    ]

    operations = [
        migrations.CreateModel(
            name="patient_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.patient"
                    ),
                ),
            ],
        ),
    ]
