# Generated by Django 5.1.1 on 2024-10-08 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_delete_doctor_delete_hospital_delete_patient_4"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "hid",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("hname", models.CharField(max_length=25)),
                ("haddr", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="doctor",
            fields=[
                ("fname", models.CharField(blank=True, max_length=50, null=True)),
                ("lname", models.CharField(blank=True, max_length=50, null=True)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "Id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("aadhar", models.BigIntegerField(blank=True, null=True)),
                (
                    "hid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.hospital"
                    ),
                ),
            ],
        ),
    ]
